spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://sumancloud.com:33897/example?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: user02
      password: New@123456
mybatis:
   mapperLocations: classpath:/mapper/*.xml
server:
  port: 8881